# Generated by Django 5.0.6 on 2025-09-29 01:33

from django.db import migrations


def assign_coordinates(apps, schema_editor):
    Taller = apps.get_model('user', 'Taller')
    coords = [
        (-34.603722, -58.381592),
        (-34.615803, -58.433298),
        (-34.560906, -58.456391),
        (-34.588303, -58.409527),
        (-34.638473, -58.364786),
    ]

    for idx, taller in enumerate(Taller.objects.all().order_by('id')):
        lat, lon = coords[idx % len(coords)]
        taller.latitud = lat
        taller.longitud = lon
        taller.save(update_fields=['latitud', 'longitud'])


def reset_coordinates(apps, schema_editor):
    Taller = apps.get_model('user', 'Taller')
    Taller.objects.update(latitud=None, longitud=None)


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_taller_latitud_taller_longitud'),
    ]

    operations = [
        migrations.RunPython(assign_coordinates, reset_coordinates),
    ]
